-------- CREATE PC_REGISTER_MEMBER --------

CREATE TABLE
    PC_REGISTER_MEMBER (
        MEMBER_ID UUID PRIMARY KEY,
        CREATED_BY VARCHAR (36) NOT NULL,
        CREATED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            LAST_MODIFIED_BY VARCHAR (36),
            LAST_MODIFIED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            DELETED BOOLEAN DEFAULT FALSE,
            MEMBER_LOGIN VARCHAR (100) NOT NULL,
            MEMBER_PASSWORD VARCHAR (100) NOT NULL,
            MEMBER_NAME VARCHAR (255) NOT NULL,
            MEMBER_STATUS INTEGER NOT NULL DEFAULT 0,
            MEMBER_EMAIL VARCHAR (100) NOT NULL,
            MEMBER_TEL VARCHAR (50),
            MEMBER_ADDRESS VARCHAR (255),
            MEMBER_PATH VARCHAR (100) NOT NULL
    );

CREATE UNIQUE INDEX IDX_PC_REGISTER_MEMBER_ID ON PC_REGISTER_MEMBER (MEMBER_ID);

-------- CREATE PC_REGISTER_PACKAGE --------

CREATE TABLE
    PC_REGISTER_PACKAGE (
        PACKAGE_ID UUID PRIMARY KEY,
        CREATED_BY VARCHAR (36) NOT NULL,
        CREATED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            LAST_MODIFIED_BY VARCHAR (36),
            LAST_MODIFIED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            DELETED BOOLEAN DEFAULT FALSE,
            ORDER_NO INTEGER,
            PACKAGE_NAME VARCHAR (100) NOT NULL,
            PACKAGE_DETAIL TEXT,
            PACKAGE_PRICE INTEGER NOT NULL DEFAULT 0,
            SHOW_STATUS INTEGER NOT NULL DEFAULT 0
    );

CREATE UNIQUE INDEX IDX_PC_REGISTER_PACKAGE_ID ON PC_REGISTER_PACKAGE (PACKAGE_ID);

-------- CREATE PC_REGISTER_PACKAGE_ITEM --------

CREATE TABLE
    PC_REGISTER_PACKAGE_ITEM (
        PACKAGE_ITEM_ID UUID PRIMARY KEY,
        CREATED_BY VARCHAR (36) NOT NULL,
        CREATED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            LAST_MODIFIED_BY VARCHAR (36),
            LAST_MODIFIED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            DELETED BOOLEAN DEFAULT FALSE,
            ORDER_NO INTEGER,
            PACKAGE_ITEM_NAME VARCHAR (255) NOT NULL,
            PACKAGE_ITEM_CODE VARCHAR (50) NOT NULL
    );

CREATE UNIQUE INDEX IDX_PC_REGISTER_PACKAGE_ITEM_ID ON PC_REGISTER_PACKAGE_ITEM (PACKAGE_ITEM_ID);

-------- CREATE PC_REGISTER_PACKAGE_LIST_ITEM --------

CREATE TABLE
    PC_REGISTER_PACKAGE_LIST_ITEM (
        PACKAGE_LIST_ITEM_ID UUID PRIMARY KEY,
        CREATED_BY VARCHAR (36) NOT NULL,
        CREATED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            LAST_MODIFIED_BY VARCHAR (36),
            LAST_MODIFIED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            DELETED BOOLEAN DEFAULT FALSE,
            PACKAGE_ID UUID NOT NULL,
            PACKAGE_ITEM_ID UUID NOT NULL,
            PACKAGE_ITEM_LIMIT INTEGER NOT NULL DEFAULT 1,
            CONSTRAINT FK_REGISTER_PACKAGE_LIST_ITEM_REGISTER_PACKAGE FOREIGN KEY (PACKAGE_ID) REFERENCES PC_REGISTER_PACKAGE (PACKAGE_ID) ON DELETE CASCADE,
            CONSTRAINT FK_REGISTER_PACKAGE_LIST_ITEM_REGISTER_PACKAGE_ITEM FOREIGN KEY (PACKAGE_ITEM_ID) REFERENCES PC_REGISTER_PACKAGE_ITEM (PACKAGE_ITEM_ID) ON DELETE CASCADE
    );

CREATE UNIQUE INDEX IDX_PC_REGISTER_PACKAGE_LIST_ITEM_ID ON PC_REGISTER_PACKAGE_LIST_ITEM (PACKAGE_LIST_ITEM_ID);

-------- CREATE PC_REGISTER_PROJECT --------

CREATE TABLE
    PC_REGISTER_PROJECT (
        PROJECT_ID UUID PRIMARY KEY,
        CREATED_BY VARCHAR (36) NOT NULL,
        CREATED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            LAST_MODIFIED_BY VARCHAR (36),
            LAST_MODIFIED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            DELETED BOOLEAN DEFAULT FALSE,
            ORDER_NO INTEGER,
            MEMBER_ID UUID NOT NULL,
            PROJECT_NAME VARCHAR (100) NOT NULL,
            PROJECT_DETAIL TEXT,
            PACKAGE_ID UUID NOT NULL,
            START_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            END_DATE TIMESTAMP
        WITH
            TIME ZONE,
            CONSTRAINT FK_PC_REGISTER_PROJECT_REGISTER_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES PC_REGISTER_MEMBER (MEMBER_ID) ON DELETE CASCADE,
            CONSTRAINT FK_PC_REGISTER_PROJECT_REGISTER_PACKAGE FOREIGN KEY (PACKAGE_ID) REFERENCES PC_REGISTER_PACKAGE (PACKAGE_ID) ON DELETE CASCADE
    );

CREATE UNIQUE INDEX IDX_PC_REGISTER_PROJECT_ID ON PC_REGISTER_PROJECT (PROJECT_ID);

-------- CREATE PC_USER --------

CREATE TABLE
    PC_USER (
        USER_ID UUID PRIMARY KEY,
        CREATED_BY VARCHAR (36) NOT NULL,
        CREATED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            LAST_MODIFIED_BY VARCHAR (36),
            LAST_MODIFIED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            DELETED BOOLEAN DEFAULT FALSE,
            USER_LOGIN VARCHAR (100) NOT NULL,
            USER_PASSWORD VARCHAR (100) NOT NULL,
            USER_NAME VARCHAR (255) NOT NULL,
            USER_STATUS INTEGER NOT NULL DEFAULT 0,
            USER_EMAIL VARCHAR (100) NOT NULL,
            USER_TEL VARCHAR (50)
    );

CREATE UNIQUE INDEX IDX_PC_USER_ID ON PC_USER (USER_ID);

-------- CREATE PC_REGISTER_PROJECT_USER --------

CREATE TABLE
    PC_REGISTER_PROJECT_USER (
        PROJECT_USER_ID UUID PRIMARY KEY,
        CREATED_BY VARCHAR (36) NOT NULL,
        CREATED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            LAST_MODIFIED_BY VARCHAR (36),
            LAST_MODIFIED_DATE TIMESTAMP
        WITH
            TIME ZONE NOT NULL,
            DELETED BOOLEAN DEFAULT FALSE,
            PROJECT_ID UUID NOT NULL,
            USER_ID UUID NOT NULL,
            CONSTRAINT FK_REGISTER_PROJECT_USER_REGISTER_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PC_REGISTER_PROJECT (PROJECT_ID) ON DELETE CASCADE,
            CONSTRAINT FK_REGISTER_PROJECT_USER_USER FOREIGN KEY (USER_ID) REFERENCES PC_USER (USER_ID) ON DELETE CASCADE
    );

CREATE UNIQUE INDEX IDX_PC_REGISTER_PROJECT_USER_ID ON PC_REGISTER_PROJECT_USER (PROJECT_USER_ID);