DROP TABLE IF EXISTS "PC_REGISTER_MEMBER";

DROP TABLE IF EXISTS "PC_REGISTER_PACKAGE";

DROP TABLE IF EXISTS "PC_REGISTER_PACKAGE_ITEM";

DROP TABLE IF EXISTS "PC_REGISTER_PACKAGE_LIST_ITEM";

DROP TABLE IF EXISTS "PC_REGISTER_PROJECT";

DROP TABLE IF EXISTS "PC_REGISTER_PROJECT_USER";

DROP TABLE IF EXISTS "PC_USER";